version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "RAZRAZ123"
      MYSQL_DATABASE: FinalProjectDB
    ports:
      - "3306:3306"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql 
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      retries: 3
      timeout: 5s
      start_period: 5s

networks:
  my_network:
    driver: bridge
